# Assigned to Dan and Sarim

'''
Link to automate on:

https://www.faxvin.com/license-plate-lookup
'''

# Generated by Selenium IDE
import pytest
import time # - This guy was causing problems
# import json - This guy was causing problems
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options

def return_info(plate): 
    # For some reason, the geckodriver for firefox is being buggy so let's stick with Chrome for now
    PATH = executable_path='C:\\Users\\sarim\\Desktop\\CS415_Project\\chromedriver.exe'
    driver = webdriver.Chrome(PATH)

    driver.get("https://www.faxvin.com/license-plate-lookup/")

    driver.set_window_size(550, 691)
    driver.find_element(By.CSS_SELECTOR, "label").click()
    driver.find_element(By.NAME, "plate").click()
    driver.find_element(By.NAME, "plate").send_keys(plate)
    driver.find_element(By.NAME, "state").click()
    dropdown = driver.find_element(By.NAME, "state")
    dropdown.find_element(By.XPATH, "//option[. = 'Illinois (IL)']").click()
    driver.find_element(By.CSS_SELECTOR, "option:nth-child(15)").click()
    driver.find_element(By.CSS_SELECTOR, "button").click()

    # Plate =
    # VIN =
    # Year =
    # Make =
    # Model =
    # Before the driver quits, we need to grab information (VIN #, Year, Make, Model) and return it, we should collect the tags for those

    # What's happening right now is that the driver is quitting right away, so we need to add like a wait or sleep function to keep that from happening quickly
    time.sleep(1000)
    driver.quit()